### ISSUE TITLE
Antidepressants / Mood boosters

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#19]
To be taken daily. Provides a large mood benefit to counter depressive traits or severe mood debuffs. Can have side effects if no longer being taken after X amount of time

**Comment by I-Knight-I** [comment]
Works perfectly. Might need balancing and requires texture.

**Comment by ghost** [comment]
Cool idea!  I'd say some of the most popular antidepressants are SSRI (selective serotonin reuptake inhibitors), e.g. sertraline (Zoloft) and fluoxetine (Prozac).  Typically you have to wait a few weeks until they're effective.

More information:
https://en.wikipedia.org/wiki/Selective_serotonin_reuptake_inhibitor#List_of_SSRIs

Taking too many SSRIs can result in [serotonin syndrome](https://en.wikipedia.org/wiki/Serotonin_syndrome)

**Comment by I-Knight-I** [comment]
Going to keep it simple as we discussed. I'd also say that a +20 mood boost is balanced enough although recipe will need adjustment.
