### ISSUE TITLE
Super antibiotics

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#20]
Last resort antibiotics used to treat infections at 90% severity or higher. Extremely costly, requires a medicine skill of 10-15+ to manufacture, rots easily and only works once per pawn.

**Comment by I-Knight-I** [comment]
Super antibiotics work but the SuperAntiHidden hediff is applied prematurely which then caps the pawns BloodFiltration stat at 150% thus not allowing the Super Antibiotics to reach 600%. Requires texture.

**Comment by ghost** [comment]
This reminds me of the antibiotic [vancomycin](https://en.wikipedia.org/wiki/Vancomycin), which is used for serious infections.  It can only be administered intravenously for most cases.

**Comment by I-Knight-I** [comment]
Reworked SuperAntibiotics so now it contains it's own scripting and C# class. Fixes bug and makes it simpler in the long run.
