### ISSUE TITLE
Aspirin for Artery Blockage

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#21]
Take daily to gradually reduce severity of artery blockage

**Comment by I-Knight-I** [comment]
Aspirin working 100%. Required new HediffCompProperties class that reduces ArteryBlockage hediff Severity by 0.05 until it's at 0.00. Artery blockage is completely removed after enough time on the medication. Requires textures, balancing and polishing.

**Comment by ghost** [comment]
Note that aspirin is typically prescribed in [coronary artery disease](https://en.wikipedia.org/wiki/Coronary_artery_disease) to prevent further clotting of the coronary arteries.  It isn't known to reduce the blockage.

Perhaps a more realistic approach would be to slow down the progression of the artery blockage hediff.

A common side effect of aspirin includes upset stomach which can be as severe as stomach ulcers and gastric bleeding.

**Comment by I-Knight-I** [comment]
I'm not sure how easy it'd be to slow down the progression of the hediff. It's definitely possible but it might require a bit of fiddling with the game's code. For now I've removed Aspirin's ability to completely remove the artery blockage so now all it does is - on consumption - **decrease** the severity of the hediff by 0.00075 until it is less than or equal to 0.0007 . The hediff increases by 0.0007 every day (base) so the aspirin is a valid way to "undo" a day's worth of severity increase. This means that daily consumption (or even every 5 days) will be beneficial to the pawn's health without making it too unrealistic or overpowered.

**Comment by I-Knight-I** [comment]
Updated in f4157a2
