### ISSUE TITLE
Brown inhalers for asthma hediff

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#22]
Take daily to lower severity of asthma hediff

**Comment by ghost** [comment]
Note that asthma in Rimworld is already treatable with in-game medicine.  It seems that the way it works is that, over time, you will be able to tend to the asthma.  Based on the treatment quality, the asthma can get better, but it won't go away and this loop continues.

IRL asthmatics have rescue inhalers and maintenance medication/inhalers.  Usually the rescue inhalers are for use when the asthma is severe, and the maintenance is for daily use to keep it managed.  It seems like, with the constant need to tend the asthma in-game, the RimWorld medicine works both as a rescue and maintenance therapy.

It seems that RW already manages asthma treatment pretty well with vanilla mechanics.

**Comment by I-Knight-I** [comment]
Closing this then. No need for additional items if in-game features are already pretty good.
