### ISSUE TITLE
Medical IV's? Shall we merge the two mods?

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#29]
Much less powerful than super antibiotics and will work always. Much simpler to manufacture too.

**Comment by ghost** [comment]
Note that many strong antibiotics, when used in the case of a life threatening infection, would be administered via IV.  Taking it by mouth would be slower and less effective and, in cases like vancomycin, aren't effective at all.

Would be interesting to merge the ideas and "fuel" the IV pole with the antibiotic.
