### ISSUE TITLE
Machines could have different textures when running

### ISSUE THREAD

**Issue by ghost** [B-Knight49/Rimworld-MedicalOverhaul#32]
Noticed this when designing the dialysis machine.  Typically when you think of dialysis machines, you picture the tubes full of blood.  But, of course, when they're not hooked up to someone, the tubes are empty.  Same with the heart-lung bypass - there's this big chamber full of blood like tomato soup that is only filled when in use.

Would be interesting to have a separate "active" texture for the machines.  For the vent, I could simply have the screen brighter when active.

**Comment by I-Knight-I** [comment]
Not entirely sure if this is possible with the current version of the game. Might require a bit of research. Similarly I was thinking that sounds whilst the machines are powered could be good but didn't want to annoy the user. Maybe something like a beeping noise?

**Comment by ghost** [comment]
I suppose if there is no vanilla example of either, it would be difficult/too much work to implement at the moment.  It's a cool idea though!  The beeping would definitely make the machines seem more immersive.

**Comment by I-Knight-I** [comment]
Just occurred to me that the Wind Turbine is a great example of this. It even demonstrates differing animation speed depending on the power output (not that we need this). If I look at the code for that then I might be able to make something of this yet...

EDIT: Nevermind. The Wind Turbine implements some really... weird features. I'm pretty sure it grows and shrinks the blades to give the illusion of spinning and so it doesn't change the animation at all.

**Comment by I-Knight-I** [comment]
Done some more research - this is really difficult. Given how small of a feature this would be, it's probably not worth the effort and time. Most people will use animated textures for large buildings and things which usually require some sort of visual output like wind turbines. 

Going to close this unless there's an easier way to do this in the future. 

EDIT: Also worth noting that performance would be negatively impacted by too many animated buildings.
