### ISSUE TITLE
Anti-Luciferium machine

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#43]
"A dispenser of dormant antimechanites used in Glitterworld hospitals. When loaded into the proper device, the antimechanites can be programmed to target existing mechanites in the patient's body."

- Possibly quest related component

- Limited charges

- Blood Bags

- Rare

**Comment by ghost** [comment]
Could work on fibrous/sensory mechanite diseases as well?

**Comment by I-Knight-I** [comment]
WIP Name: Mechanite Suffuser. 

suffuse = opposite of infuse. Essentially "remove"

**Comment by I-Knight-I** [comment]
WIP Component Name: Antinite.

Anti - mechanite = antinite

Total number of uses per component: 10. Either removing luciferium or fibrous/sensory mechanites.
