### ISSUE TITLE
Depression Expansion - Suicide?

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#49]
Depressed pawns could have a mental break that causes suicide. Suicide would cause an entire colony to become debuffed and have a mood thought with -15ish - 

"A colonist has committed suicide. The harsh reality has hit me hard..."

Could only be caused by Extreme Break Risks or Major Break Risks.

**Comment by I-Knight-I** [comment]
Depression and suicide is NOT added by Psychology mod. It's worth checking out the systems put in place by that mod to see about compatibility and ways we can integrate it smoothly in both the vanilla game AND Psychology modded game. 

Also worth noting that the creator of Psychology is the creator of Death Rattle. I don't really want to add a **dependency** on two mods - let alone two mods by the same author.

**Comment by ghost** [comment]
If you are concerned about too much feature creep and compatibility issues, perhaps it's best to just shelf this issue for the time being.  Psychology seems to be a pretty well-known mod, so I think that it would be best to avoid conflicting with it for now.
