### ISSUE TITLE
Methadone - temp replacement for hard opiates to wean pawn off of addiction 

### ISSUE THREAD

**Issue by I-Knight-I** [B-Knight49/Rimworld-MedicalOverhaul#58]
Would make it lower the pawns dependency on opiates whilst not giving them any enhanced health benefits that the drugs would otherwise offer. This'd act as the drug they're addicted to (thus removing any withdrawals) and it'd reduce their "dependency" hediff too.

**Comment by I-Knight-I** [comment]
Begun work d253b05

**Comment by I-Knight-I** [comment]
I've gotten Narcan and Methadone mixed up. Need to swap them around, will do that in upcoming commit.

**Comment by ghost** [comment]
*wean

ween is slang for wieners

**Comment by I-Knight-I** [comment]
Finished in 2ec92b2
