### ISSUE TITLE
Minor IV code issues

### ISSUE THREAD

**Issue by MissingArgumentException** [B-Knight49/Rimworld-MedicalOverhaul#72]
-You don't need to add a new stat for bleed rate, the game already has `totalBleedFactor` for the coagulator implant.

-You need to put `<isBad>false</isBad>` on your hediffs that inherit from `DiseaseBase` or things like Archotech+'s regenerator implant, or immortality from the eponymous mod will remove them.

**Comment by I-Knight-I** [comment]
This mod is no longer being worked on. It was never uploaded, was a WIP and targetted Rimworld 0.18 (If I recall correctly). I should probably archive the repo.
